name: Update README with Recent Repos

on:
  schedule:
    - cron: '0 0 * * *'  # ทุกวันเวลาเที่ยงคืน
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch recent repos
        run: |
          curl -s "https://api.github.com/users/rutchaphon123/events/public" \
          | jq -r '[.[] | select(.type=="PushEvent")] | unique_by(.repo.name) | .[:3][] | "- [\(.repo.name)](https://github.com/\(.repo.name))"' \
          > recent_repos.md

      - name: Update README
        run: |
          sed -i '/<ul id="recent-projects">/,/<\/ul>/c\<ul id="recent-projects">\n'"$(sed 's/^/- /' recent_repos.md | sed 's/^- /<li>/;s/$/<\/li>/")"'\n</ul>' README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update recent repos in README'
