name: Update README with Recent Repos

on:
  schedule:
    - cron: '0 0 * * *'  # ทุกวันเวลาเที่ยงคืน
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch recent repos
        run: |
          curl -s "https://api.github.com/users/rutchaphon123/repos?sort=pushed&direction=desc" \
          | jq -r '.[0:3][] | "[\(.full_name)](\(.html_url))"' \
          > recent_repos.md

      - name: Update README
        run: |
          echo "<ul id=\"recent-projects\">" > new_recent.md
          while read line; do
            echo "  <li>$line</li>" >> new_recent.md
          done < recent_repos.md
          echo "</ul>" >> new_recent.md
          perl -0777 -i -pe 's|<ul id="recent-projects">.*?</ul>|'"$(cat new_recent.md)"'|gs' README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update recent repos in README'
